from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from pydantic import BaseModel, Field

from core.models import ApproachBrief, ApproachSource, MethodOption, Need
from services.qwen import QwenClient
from services.vane_client import VaneClient

SYSTEM = """You are an equipment gap analyst. You have been given real web search results about the user's goal.
Use the search results to identify what equipment, tools, and components they actually need.
Prioritize items that are frequently recommended, well-reviewed, or trending in the community.
Be specific about parts, tools, and components. Consider the user's budget if provided.

APPROACH (when the goal involves choosing a method or technique):
- First identify the 2-4 popular methods/approaches the community actually discusses for this goal (e.g. for bookbinding: double fan, coptic stitch, thermal binding).
- For each: a 1-2 sentence summary and what the community says about it (community_take).
- Pick ONE recommended method for this user's situation and budget, and explain why in 1-2 sentences.
- The needs list must then assume the recommended method.
- Base methods ONLY on the provided search results — do not invent methods or community opinions.
- If the goal does not involve a method choice (e.g. a simple parts list), set approach to null.

Return a JSON object with:
- "approach": {methods: [{name, summary, community_take}], recommended, why} or null
- "needs": array of {description, rationale, priority (critical/important/nice-to-have), estimated_cost_range}"""


# Deliberately NOT the full Need model: Need embeds ProductCard, and a schema
# that advertises product fields invites the LLM to fabricate example products
# (dead amazon links, example.com images) at analyze time, before any real
# search has run. NB: a docstring here would leak into the LLM-facing schema.
class NeedSpec(BaseModel):
    description: str
    rationale: str = ""
    priority: Literal["critical", "important", "nice-to-have"] = "important"
    estimated_cost_range: str = ""


# LLM-facing approach schema: text only — source links are attached
# server-side from the real Vane results, never generated by the model
class ApproachSpec(BaseModel):
    methods: list[MethodOption] = Field(default_factory=list)
    recommended: str = ""
    why: str = ""


class GapAnalysisResult(BaseModel):
    needs: list[NeedSpec] = Field(default_factory=list)
    approach: ApproachSpec | None = None


@dataclass
class GapAnalysis:
    needs: list[Need]
    approach: ApproachBrief | None


async def analyze_gaps(
    qwen: QwenClient,
    goal: str,
    equipment: str,
    wiki_context: str,
    budget: float | None,
    vane: VaneClient | None = None,
) -> GapAnalysis:
    web_context = ""
    vane_sources = []
    if vane:
        try:
            result = await vane.search(
                query=f"{goal} recommended setup guide what to buy reddit",
                optimization_mode="quality",
                system_instructions="Find buying guides, community recommendations, and trending setups. Include Reddit, YouTube, and forum posts.",
            )
            vane_sources = result.sources
            web_context = f"Web research results:\n{result.message}\n\nSources:\n"
            for s in result.sources[:10]:
                web_context += f"- {s.title} ({s.url}): {s.content[:200]}\n"
        except Exception as e:
            import logging
            logging.error(f"Vane search failed during gap analysis: {e}")

    user_prompt = f"""Goal: {goal}

{web_context}

Current equipment:
{equipment or "Not specified"}

Project context:
{wiki_context or "None"}

Budget: {"$" + str(budget) if budget else "Not specified"}

Based on the web research and community recommendations above: first identify the popular methods/approaches (if the goal involves choosing one) and recommend the best fit, then identify what equipment, parts, or tools are needed for the recommended approach. Prioritize items that real users recommend."""

    result = await qwen.generate(
        system=SYSTEM,
        user=user_prompt,
        response_model=GapAnalysisResult,
    )

    needs = [
        Need(
            description=spec.description,
            rationale=spec.rationale,
            priority=spec.priority,
            estimated_cost_range=spec.estimated_cost_range,
        )
        for spec in result.needs[:5]
    ]

    approach: ApproachBrief | None = None
    if result.approach and result.approach.methods:
        approach = ApproachBrief(
            methods=result.approach.methods[:4],
            recommended=result.approach.recommended,
            why=result.approach.why,
            # Real URLs from the actual search — the model never produces these
            sources=[
                ApproachSource(title=s.title or s.url, url=s.url)
                for s in vane_sources[:3]
                if s.url
            ],
        )

    return GapAnalysis(needs=needs, approach=approach)
